// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cronos/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ContractByDenomRequest is the request type of ContractByDenom call
type ContractByDenomRequest struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *ContractByDenomRequest) Reset()         { *m = ContractByDenomRequest{} }
func (m *ContractByDenomRequest) String() string { return proto.CompactTextString(m) }
func (*ContractByDenomRequest) ProtoMessage()    {}
func (*ContractByDenomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4ed0fd688c48372, []int{0}
}
func (m *ContractByDenomRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContractByDenomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ContractByDenomRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ContractByDenomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractByDenomRequest.Merge(m, src)
}
func (m *ContractByDenomRequest) XXX_Size() int {
	return m.Size()
}
func (m *ContractByDenomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractByDenomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContractByDenomRequest proto.InternalMessageInfo

func (m *ContractByDenomRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// ContractByDenomRequest is the response type of ContractByDenom call
type ContractByDenomResponse struct {
	Contract     string `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	AutoContract string `protobuf:"bytes,2,opt,name=auto_contract,json=autoContract,proto3" json:"auto_contract,omitempty"`
}

func (m *ContractByDenomResponse) Reset()         { *m = ContractByDenomResponse{} }
func (m *ContractByDenomResponse) String() string { return proto.CompactTextString(m) }
func (*ContractByDenomResponse) ProtoMessage()    {}
func (*ContractByDenomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4ed0fd688c48372, []int{1}
}
func (m *ContractByDenomResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContractByDenomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ContractByDenomResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ContractByDenomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractByDenomResponse.Merge(m, src)
}
func (m *ContractByDenomResponse) XXX_Size() int {
	return m.Size()
}
func (m *ContractByDenomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractByDenomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContractByDenomResponse proto.InternalMessageInfo

func (m *ContractByDenomResponse) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *ContractByDenomResponse) GetAutoContract() string {
	if m != nil {
		return m.AutoContract
	}
	return ""
}

// DenomByContractRequest is the request type of DenomByContract call
type DenomByContractRequest struct {
	Contract string `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
}

func (m *DenomByContractRequest) Reset()         { *m = DenomByContractRequest{} }
func (m *DenomByContractRequest) String() string { return proto.CompactTextString(m) }
func (*DenomByContractRequest) ProtoMessage()    {}
func (*DenomByContractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4ed0fd688c48372, []int{2}
}
func (m *DenomByContractRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DenomByContractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DenomByContractRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DenomByContractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenomByContractRequest.Merge(m, src)
}
func (m *DenomByContractRequest) XXX_Size() int {
	return m.Size()
}
func (m *DenomByContractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DenomByContractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DenomByContractRequest proto.InternalMessageInfo

func (m *DenomByContractRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

// DenomByContractResponse is the response type of DenomByContract call
type DenomByContractResponse struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *DenomByContractResponse) Reset()         { *m = DenomByContractResponse{} }
func (m *DenomByContractResponse) String() string { return proto.CompactTextString(m) }
func (*DenomByContractResponse) ProtoMessage()    {}
func (*DenomByContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4ed0fd688c48372, []int{3}
}
func (m *DenomByContractResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DenomByContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DenomByContractResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DenomByContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenomByContractResponse.Merge(m, src)
}
func (m *DenomByContractResponse) XXX_Size() int {
	return m.Size()
}
func (m *DenomByContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DenomByContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DenomByContractResponse proto.InternalMessageInfo

func (m *DenomByContractResponse) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func init() {
	proto.RegisterType((*ContractByDenomRequest)(nil), "cronos.ContractByDenomRequest")
	proto.RegisterType((*ContractByDenomResponse)(nil), "cronos.ContractByDenomResponse")
	proto.RegisterType((*DenomByContractRequest)(nil), "cronos.DenomByContractRequest")
	proto.RegisterType((*DenomByContractResponse)(nil), "cronos.DenomByContractResponse")
}

func init() { proto.RegisterFile("cronos/query.proto", fileDescriptor_d4ed0fd688c48372) }

var fileDescriptor_d4ed0fd688c48372 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcd, 0x4a, 0xeb, 0x40,
	0x14, 0xc7, 0x9b, 0x42, 0xcb, 0xbd, 0xc3, 0xbd, 0x14, 0x86, 0x4b, 0x7b, 0x09, 0x12, 0x25, 0x8a,
	0x5f, 0xd8, 0x0c, 0x51, 0x9f, 0xa0, 0xba, 0x73, 0x65, 0x97, 0xdd, 0x94, 0x49, 0x1c, 0xd2, 0x80,
	0x9d, 0x93, 0x66, 0x26, 0xc5, 0x50, 0x0a, 0xa2, 0x2f, 0x50, 0xf0, 0xa5, 0x5c, 0x16, 0xdc, 0xb8,
	0x94, 0xd6, 0x07, 0x91, 0x4c, 0x32, 0xad, 0xf4, 0xc3, 0x55, 0xe6, 0x9c, 0xf9, 0x9f, 0x73, 0x7e,
	0xe7, 0x9f, 0x41, 0xd8, 0x8f, 0x81, 0x83, 0x20, 0x83, 0x84, 0xc5, 0xa9, 0x13, 0xc5, 0x20, 0x01,
	0x57, 0xf3, 0x9c, 0xb9, 0x13, 0x00, 0x04, 0xf7, 0x8c, 0xd0, 0x28, 0x24, 0x94, 0x73, 0x90, 0x54,
	0x86, 0xc0, 0x45, 0xae, 0x32, 0x4f, 0x7d, 0x10, 0x7d, 0x10, 0xc4, 0xa3, 0x82, 0xe5, 0xe5, 0x64,
	0xe8, 0x7a, 0x4c, 0x52, 0x97, 0x44, 0x34, 0x08, 0xb9, 0x12, 0xe7, 0x5a, 0xdb, 0x41, 0xf5, 0x2b,
	0xe0, 0x32, 0xa6, 0xbe, 0x6c, 0xa5, 0xd7, 0x8c, 0x43, 0xbf, 0xcd, 0x06, 0x09, 0x13, 0x12, 0xff,
	0x43, 0x95, 0xbb, 0x2c, 0xfe, 0x6f, 0xec, 0x19, 0xc7, 0xbf, 0xdb, 0x79, 0x60, 0x77, 0x50, 0x63,
	0x4d, 0x2f, 0x22, 0xe0, 0x82, 0x61, 0x13, 0xfd, 0xf2, 0x8b, 0xab, 0xa2, 0x66, 0x11, 0xe3, 0x7d,
	0xf4, 0x97, 0x26, 0x12, 0xba, 0x0b, 0x41, 0x59, 0x09, 0xfe, 0x64, 0x49, 0xdd, 0xcf, 0xbe, 0x44,
	0x75, 0xd5, 0xb1, 0x95, 0xea, 0x94, 0x66, 0xf9, 0xa1, 0xb5, 0x4d, 0x50, 0x63, 0xad, 0xaa, 0x20,
	0xda, 0xb8, 0xc2, 0xf9, 0xa4, 0x8c, 0x2a, 0xb7, 0x99, 0x2b, 0xf8, 0xd1, 0x40, 0xb5, 0x95, 0x6d,
	0xb0, 0xe5, 0xe4, 0x1e, 0x3b, 0x9b, 0x6d, 0x31, 0x77, 0xb7, 0xde, 0xe7, 0x43, 0xed, 0xb3, 0xa7,
	0xb7, 0xcf, 0x97, 0xf2, 0x21, 0x3e, 0x20, 0xc5, 0x0f, 0x1c, 0xba, 0x44, 0xc3, 0x76, 0xbd, 0xb4,
	0xab, 0x20, 0xc8, 0x48, 0x7d, 0xc6, 0xf8, 0xd9, 0x40, 0xb5, 0x15, 0xfc, 0x25, 0xc2, 0x66, 0x37,
	0x96, 0x08, 0x5b, 0xf6, 0xb6, 0x89, 0x42, 0x38, 0xc1, 0x47, 0xdf, 0x10, 0xd4, 0xbc, 0x6c, 0xbe,
	0x66, 0x21, 0x23, 0x7d, 0x1a, 0xb7, 0x6e, 0x5e, 0x67, 0x96, 0x31, 0x9d, 0x59, 0xc6, 0xc7, 0xcc,
	0x32, 0x26, 0x73, 0xab, 0x34, 0x9d, 0x5b, 0xa5, 0xf7, 0xb9, 0x55, 0xea, 0xb8, 0x41, 0x28, 0x7b,
	0x89, 0xe7, 0xf8, 0xd0, 0x27, 0x7e, 0x9c, 0x46, 0x12, 0x9a, 0x10, 0x07, 0x4d, 0xbf, 0x47, 0x43,
	0xae, 0xbb, 0x3f, 0xe8, 0x83, 0x4c, 0x23, 0x26, 0xbc, 0xaa, 0x7a, 0x59, 0x17, 0x5f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xf7, 0xcb, 0x7f, 0xa6, 0xc1, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// ContractByDenom queries contract addresses by native denom
	ContractByDenom(ctx context.Context, in *ContractByDenomRequest, opts ...grpc.CallOption) (*ContractByDenomResponse, error)
	// DenomByContract queries native denom by contract address
	DenomByContract(ctx context.Context, in *DenomByContractRequest, opts ...grpc.CallOption) (*DenomByContractResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ContractByDenom(ctx context.Context, in *ContractByDenomRequest, opts ...grpc.CallOption) (*ContractByDenomResponse, error) {
	out := new(ContractByDenomResponse)
	err := c.cc.Invoke(ctx, "/cronos.Query/ContractByDenom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DenomByContract(ctx context.Context, in *DenomByContractRequest, opts ...grpc.CallOption) (*DenomByContractResponse, error) {
	out := new(DenomByContractResponse)
	err := c.cc.Invoke(ctx, "/cronos.Query/DenomByContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// ContractByDenom queries contract addresses by native denom
	ContractByDenom(context.Context, *ContractByDenomRequest) (*ContractByDenomResponse, error)
	// DenomByContract queries native denom by contract address
	DenomByContract(context.Context, *DenomByContractRequest) (*DenomByContractResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ContractByDenom(ctx context.Context, req *ContractByDenomRequest) (*ContractByDenomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContractByDenom not implemented")
}
func (*UnimplementedQueryServer) DenomByContract(ctx context.Context, req *DenomByContractRequest) (*DenomByContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DenomByContract not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ContractByDenom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContractByDenomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ContractByDenom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cronos.Query/ContractByDenom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ContractByDenom(ctx, req.(*ContractByDenomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DenomByContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DenomByContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DenomByContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cronos.Query/DenomByContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DenomByContract(ctx, req.(*DenomByContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cronos.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ContractByDenom",
			Handler:    _Query_ContractByDenom_Handler,
		},
		{
			MethodName: "DenomByContract",
			Handler:    _Query_DenomByContract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cronos/query.proto",
}

func (m *ContractByDenomRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContractByDenomRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ContractByDenomRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ContractByDenomResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContractByDenomResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ContractByDenomResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AutoContract) > 0 {
		i -= len(m.AutoContract)
		copy(dAtA[i:], m.AutoContract)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AutoContract)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Contract) > 0 {
		i -= len(m.Contract)
		copy(dAtA[i:], m.Contract)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Contract)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DenomByContractRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DenomByContractRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DenomByContractRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Contract) > 0 {
		i -= len(m.Contract)
		copy(dAtA[i:], m.Contract)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Contract)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DenomByContractResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DenomByContractResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DenomByContractResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ContractByDenomRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *ContractByDenomResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Contract)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.AutoContract)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *DenomByContractRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Contract)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *DenomByContractResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ContractByDenomRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContractByDenomRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContractByDenomRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ContractByDenomResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContractByDenomResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContractByDenomResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutoContract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AutoContract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DenomByContractRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DenomByContractRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DenomByContractRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DenomByContractResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DenomByContractResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DenomByContractResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
