// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cronos/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgConvertToEvmTokens represents a message to convert ibc coins to evm coins.
type MsgConvertTokens struct {
	Address string                                   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount  github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *MsgConvertTokens) Reset()         { *m = MsgConvertTokens{} }
func (m *MsgConvertTokens) String() string { return proto.CompactTextString(m) }
func (*MsgConvertTokens) ProtoMessage()    {}
func (*MsgConvertTokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e09e4eabb18884, []int{0}
}
func (m *MsgConvertTokens) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConvertTokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConvertTokens.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConvertTokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConvertTokens.Merge(m, src)
}
func (m *MsgConvertTokens) XXX_Size() int {
	return m.Size()
}
func (m *MsgConvertTokens) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConvertTokens.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConvertTokens proto.InternalMessageInfo

func (m *MsgConvertTokens) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgConvertTokens) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

// MsgConvertToIbcTokens represents a message to convert evm coins to ibc coins.
type MsgSendToCryptoOrg struct {
	From   string                                   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To     string                                   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *MsgSendToCryptoOrg) Reset()         { *m = MsgSendToCryptoOrg{} }
func (m *MsgSendToCryptoOrg) String() string { return proto.CompactTextString(m) }
func (*MsgSendToCryptoOrg) ProtoMessage()    {}
func (*MsgSendToCryptoOrg) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e09e4eabb18884, []int{1}
}
func (m *MsgSendToCryptoOrg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendToCryptoOrg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendToCryptoOrg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendToCryptoOrg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendToCryptoOrg.Merge(m, src)
}
func (m *MsgSendToCryptoOrg) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendToCryptoOrg) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendToCryptoOrg.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendToCryptoOrg proto.InternalMessageInfo

func (m *MsgSendToCryptoOrg) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *MsgSendToCryptoOrg) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *MsgSendToCryptoOrg) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

// MsgMultiSendResponse defines the MsgConvert response type.
type MsgConvertResponse struct {
}

func (m *MsgConvertResponse) Reset()         { *m = MsgConvertResponse{} }
func (m *MsgConvertResponse) String() string { return proto.CompactTextString(m) }
func (*MsgConvertResponse) ProtoMessage()    {}
func (*MsgConvertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e09e4eabb18884, []int{2}
}
func (m *MsgConvertResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConvertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConvertResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConvertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConvertResponse.Merge(m, src)
}
func (m *MsgConvertResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgConvertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConvertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConvertResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgConvertTokens)(nil), "cryptoorgchain.cronos.cronos.MsgConvertTokens")
	proto.RegisterType((*MsgSendToCryptoOrg)(nil), "cryptoorgchain.cronos.cronos.MsgSendToCryptoOrg")
	proto.RegisterType((*MsgConvertResponse)(nil), "cryptoorgchain.cronos.cronos.MsgConvertResponse")
}

func init() { proto.RegisterFile("cronos/tx.proto", fileDescriptor_28e09e4eabb18884) }

var fileDescriptor_28e09e4eabb18884 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xbd, 0x6e, 0xe2, 0x40,
	0x10, 0xc7, 0xbd, 0xe6, 0xc4, 0xe9, 0xf6, 0x74, 0xc7, 0x69, 0x45, 0xe1, 0x43, 0x91, 0x41, 0x54,
	0x34, 0xec, 0x02, 0x79, 0x03, 0x28, 0x23, 0x14, 0x89, 0x50, 0xa5, 0xf3, 0xc7, 0x66, 0xb1, 0x90,
	0x77, 0x9c, 0xdd, 0x05, 0xc1, 0x5b, 0x24, 0x0f, 0x90, 0x17, 0xc8, 0x93, 0x50, 0x52, 0xa6, 0x4a,
	0x22, 0x78, 0x80, 0xbc, 0x42, 0xc4, 0xda, 0x48, 0x84, 0x22, 0x1f, 0x45, 0xaa, 0x19, 0x7b, 0x66,
	0x7e, 0xf3, 0xf7, 0xdf, 0x83, 0x2b, 0x91, 0x02, 0x09, 0x9a, 0x99, 0x05, 0xcd, 0x14, 0x18, 0x20,
	0x27, 0x91, 0x5a, 0x66, 0x06, 0x40, 0x89, 0x68, 0x12, 0x24, 0x92, 0xe6, 0xf5, 0x22, 0xd4, 0xaa,
	0x02, 0x04, 0xd8, 0x46, 0xb6, 0xcb, 0xf2, 0x99, 0x9a, 0x1f, 0x81, 0x4e, 0x41, 0xb3, 0x30, 0xd0,
	0x9c, 0xcd, 0xbb, 0x21, 0x37, 0x41, 0x97, 0x45, 0x90, 0xc8, 0xbc, 0xde, 0xbc, 0x45, 0xf8, 0xdf,
	0x50, 0x8b, 0x01, 0xc8, 0x39, 0x57, 0x66, 0x0c, 0x53, 0x2e, 0x35, 0xf1, 0xf0, 0xcf, 0x20, 0x8e,
	0x15, 0xd7, 0xda, 0x43, 0x0d, 0xd4, 0xfa, 0x35, 0xda, 0x3f, 0x92, 0x08, 0x97, 0x83, 0x14, 0x66,
	0xd2, 0x78, 0x6e, 0xa3, 0xd4, 0xfa, 0xdd, 0xfb, 0x4f, 0x73, 0x3e, 0xdd, 0xf1, 0x69, 0xc1, 0xa7,
	0x03, 0x48, 0x64, 0xbf, 0xb3, 0x7a, 0xac, 0x3b, 0xf7, 0x4f, 0xf5, 0x96, 0x48, 0xcc, 0x64, 0x16,
	0xd2, 0x08, 0x52, 0x56, 0x88, 0xc9, 0x43, 0x5b, 0xc7, 0x53, 0x66, 0x96, 0x19, 0xd7, 0x76, 0x40,
	0x8f, 0x0a, 0x74, 0xf3, 0x0e, 0x61, 0x32, 0xd4, 0xe2, 0x82, 0xcb, 0x78, 0x0c, 0x03, 0xfb, 0xcd,
	0xe7, 0x4a, 0x10, 0x82, 0x7f, 0x5c, 0x29, 0x48, 0x0b, 0x49, 0x36, 0x27, 0x7f, 0xb1, 0x6b, 0xc0,
	0x73, 0xed, 0x1b, 0xd7, 0xc0, 0x81, 0xbe, 0xd2, 0xf7, 0xe9, 0xab, 0x5a, 0x79, 0x85, 0x65, 0x23,
	0xae, 0x33, 0x90, 0x9a, 0xf7, 0x5e, 0x10, 0x2e, 0x0d, 0xb5, 0x20, 0xd7, 0xf8, 0xcf, 0x5b, 0x37,
	0x29, 0x7d, 0xef, 0xbf, 0xd1, 0x63, 0xf7, 0x6b, 0x9d, 0xcf, 0xf6, 0xef, 0x57, 0x93, 0x19, 0xae,
	0x1c, 0x9b, 0xf5, 0x31, 0xe4, 0x68, 0xe2, 0xeb, 0x6b, 0xfb, 0x67, 0xab, 0x8d, 0x8f, 0xd6, 0x1b,
	0x1f, 0x3d, 0x6f, 0x7c, 0x74, 0xb3, 0xf5, 0x9d, 0xf5, 0xd6, 0x77, 0x1e, 0xb6, 0xbe, 0x73, 0xd9,
	0x3d, 0xf4, 0xd4, 0x52, 0xdb, 0xa0, 0x44, 0xdb, 0x72, 0x59, 0x71, 0xd6, 0x8b, 0x7d, 0x62, 0x2d,
	0x0e, 0xcb, 0xf6, 0x1e, 0x4f, 0x5f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x71, 0x33, 0x71, 0x75, 0xf6,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Send defines a method for converting ibc coins to Cronos coins.
	ConvertTokens(ctx context.Context, in *MsgConvertTokens, opts ...grpc.CallOption) (*MsgConvertResponse, error)
	// Send defines a method to send coins to Crypto.org chain
	SendToCryptoOrg(ctx context.Context, in *MsgSendToCryptoOrg, opts ...grpc.CallOption) (*MsgConvertResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ConvertTokens(ctx context.Context, in *MsgConvertTokens, opts ...grpc.CallOption) (*MsgConvertResponse, error) {
	out := new(MsgConvertResponse)
	err := c.cc.Invoke(ctx, "/cryptoorgchain.cronos.cronos.Msg/ConvertTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SendToCryptoOrg(ctx context.Context, in *MsgSendToCryptoOrg, opts ...grpc.CallOption) (*MsgConvertResponse, error) {
	out := new(MsgConvertResponse)
	err := c.cc.Invoke(ctx, "/cryptoorgchain.cronos.cronos.Msg/SendToCryptoOrg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Send defines a method for converting ibc coins to Cronos coins.
	ConvertTokens(context.Context, *MsgConvertTokens) (*MsgConvertResponse, error)
	// Send defines a method to send coins to Crypto.org chain
	SendToCryptoOrg(context.Context, *MsgSendToCryptoOrg) (*MsgConvertResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ConvertTokens(ctx context.Context, req *MsgConvertTokens) (*MsgConvertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertTokens not implemented")
}
func (*UnimplementedMsgServer) SendToCryptoOrg(ctx context.Context, req *MsgSendToCryptoOrg) (*MsgConvertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToCryptoOrg not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ConvertTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgConvertTokens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ConvertTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cryptoorgchain.cronos.cronos.Msg/ConvertTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ConvertTokens(ctx, req.(*MsgConvertTokens))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SendToCryptoOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendToCryptoOrg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendToCryptoOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cryptoorgchain.cronos.cronos.Msg/SendToCryptoOrg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendToCryptoOrg(ctx, req.(*MsgSendToCryptoOrg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cryptoorgchain.cronos.cronos.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertTokens",
			Handler:    _Msg_ConvertTokens_Handler,
		},
		{
			MethodName: "SendToCryptoOrg",
			Handler:    _Msg_SendToCryptoOrg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cronos/tx.proto",
}

func (m *MsgConvertTokens) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConvertTokens) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConvertTokens) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendToCryptoOrg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendToCryptoOrg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendToCryptoOrg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.To) > 0 {
		i -= len(m.To)
		copy(dAtA[i:], m.To)
		i = encodeVarintTx(dAtA, i, uint64(len(m.To)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintTx(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgConvertResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConvertResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConvertResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgConvertTokens) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgSendToCryptoOrg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.To)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgConvertResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgConvertTokens) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConvertTokens: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConvertTokens: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendToCryptoOrg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendToCryptoOrg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendToCryptoOrg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.To = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConvertResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConvertResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConvertResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
