run:
  tests: true
  timeout: 10m
  sort-results: true
  allow-parallel-runners: true
  exclude-dir: testutil/testdata_pulsar
  concurrency: 4

linters:
  disable-all: true
  enable:
    - depguard
    - dogsled
    - exportloopref
    - goconst
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "ST1003:"
      linters:
        - stylecheck
    # FIXME: Disabled until golangci-lint updates stylecheck with this fix:
    # https://github.com/dominikh/go-tools/issues/389
    - text: "ST1016:"
      linters:
        - stylecheck
    - path: "migrations"
      text: "SA1019:"
      linters:
        - staticcheck
    - text: "leading space"
      linters:
        - nolintlint

  max-issues-per-linter: 10000
  max-same-issues: 10000

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/crypto-org-chain/cronos
          - cosmossdk.io/errors
          - cosmossdk.io/math
          - github.com/armon/go-metrics
          - github.com/cosmos/cosmos-sdk
          - github.com/cosmos/ibc-go
          - github.com/ethereum/go-ethereum
          - github.com/evmos/ethermint
          - github.com/gorilla/mux
          - github.com/grpc-ecosystem/grpc-gateway/runtime
          - github.com/linxGnu/grocksdb
          - github.com/peggyjv/gravity-bridge/module
          - github.com/rakyll/statik/fs
          - github.com/spf13
          - github.com/stretchr/testify/require
          - github.com/tendermint/tendermint
          - github.com/tendermint/tm-db
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/crypto-org-chain/cronos
          - cosmossdk.io/errors
          - cosmossdk.io/math
          - github.com/armon/go-metrics
          - github.com/cosmos/cosmos-sdk
          - github.com/cosmos/ibc-go
          - github.com/ethereum/go-ethereum
          - github.com/evmos/ethermint
          - github.com/peggyjv/gravity-bridge/module
          - github.com/stretchr/testify/require
          - github.com/tendermint/tendermint
          - github.com/tendermint/tm-db
          - github.com/stretchr/testify
