cronos_777-1:
  cmd: cronosd
  start-flags: "--trace"
  app-config:
    minimum-gas-prices: 0basetcro
    json-rpc:
      address: "0.0.0.0:{EVMRPC_PORT}"
      ws-address: "0.0.0.0:{EVMRPC_PORT_WS}"
      api: "eth,net,web3,debug,cronos"
    evm:
      max-tx-gas-wanted: 0
  validators:
    - coins: 1000000000000000000stake,10000000000000000000000basetcro
      staked: 1000000000000000000stake
      mnemonic: visit craft resemble online window solution west chuckle music diesel vital settle comic tribe project blame bulb armed flower region sausage mercy arrive release
    - coins: 1000000000000000000stake,10000000000000000000000basetcro
      staked: 1000000000000000000stake
      mnemonic: direct travel shrug hand twice agent sail sell jump phone velvet pilot mango charge usual multiply orient garment bleak virtual action mention panda vast
  accounts:
    - name: community
      coins: 10000000000000000000000basetcro
      mnemonic: "notable error gospel wave pair ugly measure elite toddler cost various fly make eye ketchup despair slab throw tribe swarm word fruit into inmate"

  genesis:
    consensus_params:
      block:
        max_bytes: "1048576"
        max_gas: "815000"
    app_state:
      evm:
        params:
          evm_denom: basetcro
      gov:
        voting_params:
          voting_period: "10s"
        deposit_params:
          max_deposit_period: "10s"
          min_deposit:
            - denom: "basetcro"
              amount: "1"
      transfer:
        params:
          receive_enabled: true
          send_enabled: true
      feemarket:
        params:
          no_base_fee: false
          initial_base_fee: 100000000000
