// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: attestation/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ForcedTxType defines the type of forced transaction
type ForcedTxType int32

const (
	// Normal forced transaction
	ForcedTxTypeNormal ForcedTxType = 0
	// Governance-related operation
	ForcedTxTypeGovernance ForcedTxType = 1
	// Escape hatch / emergency withdrawal
	ForcedTxTypeEscapeHatch ForcedTxType = 2
	// Emergency system operation
	ForcedTxTypeEmergency ForcedTxType = 3
)

var ForcedTxType_name = map[int32]string{
	0: "FORCED_TX_TYPE_NORMAL",
	1: "FORCED_TX_TYPE_GOVERNANCE",
	2: "FORCED_TX_TYPE_ESCAPE_HATCH",
	3: "FORCED_TX_TYPE_EMERGENCY",
}

var ForcedTxType_value = map[string]int32{
	"FORCED_TX_TYPE_NORMAL":       0,
	"FORCED_TX_TYPE_GOVERNANCE":   1,
	"FORCED_TX_TYPE_ESCAPE_HATCH": 2,
	"FORCED_TX_TYPE_EMERGENCY":    3,
}

func (x ForcedTxType) String() string {
	return proto.EnumName(ForcedTxType_name, int32(x))
}

func (ForcedTxType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8903721ed34b385d, []int{0}
}

// MsgSubmitBlockAttestation represents block data forwarded from EVM chain
type MsgSubmitBlockAttestation struct {
	// Relayer submitting the attestation
	Relayer string `protobuf:"bytes,1,opt,name=relayer,proto3" json:"relayer,omitempty"`
	// Source chain ID (e.g., "cronos_25-1")
	ChainId string `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Block height
	BlockHeight uint64 `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// ABCI RequestFinalizeBlock data (encoded)
	RequestFinalizeBlock []byte `protobuf:"bytes,4,opt,name=request_finalize_block,json=requestFinalizeBlock,proto3" json:"request_finalize_block,omitempty"`
	// ABCI ResponseFinalizeBlock data (encoded)
	ResponseFinalizeBlock []byte `protobuf:"bytes,5,opt,name=response_finalize_block,json=responseFinalizeBlock,proto3" json:"response_finalize_block,omitempty"`
	// Block timestamp
	Timestamp int64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Relayer signature over the block data
	Signature []byte `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *MsgSubmitBlockAttestation) Reset()         { *m = MsgSubmitBlockAttestation{} }
func (m *MsgSubmitBlockAttestation) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitBlockAttestation) ProtoMessage()    {}
func (*MsgSubmitBlockAttestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_8903721ed34b385d, []int{0}
}
func (m *MsgSubmitBlockAttestation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitBlockAttestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitBlockAttestation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitBlockAttestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitBlockAttestation.Merge(m, src)
}
func (m *MsgSubmitBlockAttestation) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitBlockAttestation) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitBlockAttestation.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitBlockAttestation proto.InternalMessageInfo

func (m *MsgSubmitBlockAttestation) GetRelayer() string {
	if m != nil {
		return m.Relayer
	}
	return ""
}

func (m *MsgSubmitBlockAttestation) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *MsgSubmitBlockAttestation) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *MsgSubmitBlockAttestation) GetRequestFinalizeBlock() []byte {
	if m != nil {
		return m.RequestFinalizeBlock
	}
	return nil
}

func (m *MsgSubmitBlockAttestation) GetResponseFinalizeBlock() []byte {
	if m != nil {
		return m.ResponseFinalizeBlock
	}
	return nil
}

func (m *MsgSubmitBlockAttestation) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MsgSubmitBlockAttestation) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// MsgSubmitBlockAttestationResponse is the response for submitting block attestation
type MsgSubmitBlockAttestationResponse struct {
	// Attestation ID assigned by the chain
	AttestationId uint64 `protobuf:"varint,1,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
	// Whether the block achieved finality immediately
	Finalized bool `protobuf:"varint,2,opt,name=finalized,proto3" json:"finalized,omitempty"`
}

func (m *MsgSubmitBlockAttestationResponse) Reset()         { *m = MsgSubmitBlockAttestationResponse{} }
func (m *MsgSubmitBlockAttestationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitBlockAttestationResponse) ProtoMessage()    {}
func (*MsgSubmitBlockAttestationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8903721ed34b385d, []int{1}
}
func (m *MsgSubmitBlockAttestationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitBlockAttestationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitBlockAttestationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitBlockAttestationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitBlockAttestationResponse.Merge(m, src)
}
func (m *MsgSubmitBlockAttestationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitBlockAttestationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitBlockAttestationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitBlockAttestationResponse proto.InternalMessageInfo

func (m *MsgSubmitBlockAttestationResponse) GetAttestationId() uint64 {
	if m != nil {
		return m.AttestationId
	}
	return 0
}

func (m *MsgSubmitBlockAttestationResponse) GetFinalized() bool {
	if m != nil {
		return m.Finalized
	}
	return false
}

// MsgSubmitBatchBlockAttestation submits multiple block attestations
type MsgSubmitBatchBlockAttestation struct {
	// Relayer submitting the attestations
	Relayer string `protobuf:"bytes,1,opt,name=relayer,proto3" json:"relayer,omitempty"`
	// Source chain ID
	ChainId string `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// List of block attestations
	Attestations []*BlockAttestationData `protobuf:"bytes,3,rep,name=attestations,proto3" json:"attestations,omitempty"`
}

func (m *MsgSubmitBatchBlockAttestation) Reset()         { *m = MsgSubmitBatchBlockAttestation{} }
func (m *MsgSubmitBatchBlockAttestation) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitBatchBlockAttestation) ProtoMessage()    {}
func (*MsgSubmitBatchBlockAttestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_8903721ed34b385d, []int{2}
}
func (m *MsgSubmitBatchBlockAttestation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitBatchBlockAttestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitBatchBlockAttestation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitBatchBlockAttestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitBatchBlockAttestation.Merge(m, src)
}
func (m *MsgSubmitBatchBlockAttestation) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitBatchBlockAttestation) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitBatchBlockAttestation.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitBatchBlockAttestation proto.InternalMessageInfo

func (m *MsgSubmitBatchBlockAttestation) GetRelayer() string {
	if m != nil {
		return m.Relayer
	}
	return ""
}

func (m *MsgSubmitBatchBlockAttestation) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *MsgSubmitBatchBlockAttestation) GetAttestations() []*BlockAttestationData {
	if m != nil {
		return m.Attestations
	}
	return nil
}

// BlockAttestationData contains the data for a single block attestation
type BlockAttestationData struct {
	// Block height
	BlockHeight uint64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// ABCI RequestFinalizeBlock data (encoded)
	RequestFinalizeBlock []byte `protobuf:"bytes,2,opt,name=request_finalize_block,json=requestFinalizeBlock,proto3" json:"request_finalize_block,omitempty"`
	// ABCI ResponseFinalizeBlock data (encoded)
	ResponseFinalizeBlock []byte `protobuf:"bytes,3,opt,name=response_finalize_block,json=responseFinalizeBlock,proto3" json:"response_finalize_block,omitempty"`
	// Block timestamp
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *BlockAttestationData) Reset()         { *m = BlockAttestationData{} }
func (m *BlockAttestationData) String() string { return proto.CompactTextString(m) }
func (*BlockAttestationData) ProtoMessage()    {}
func (*BlockAttestationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8903721ed34b385d, []int{3}
}
func (m *BlockAttestationData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlockAttestationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlockAttestationData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BlockAttestationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockAttestationData.Merge(m, src)
}
func (m *BlockAttestationData) XXX_Size() int {
	return m.Size()
}
func (m *BlockAttestationData) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockAttestationData.DiscardUnknown(m)
}

var xxx_messageInfo_BlockAttestationData proto.InternalMessageInfo

func (m *BlockAttestationData) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *BlockAttestationData) GetRequestFinalizeBlock() []byte {
	if m != nil {
		return m.RequestFinalizeBlock
	}
	return nil
}

func (m *BlockAttestationData) GetResponseFinalizeBlock() []byte {
	if m != nil {
		return m.ResponseFinalizeBlock
	}
	return nil
}

func (m *BlockAttestationData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// MsgSubmitBatchBlockAttestationResponse is the response for batch submission
type MsgSubmitBatchBlockAttestationResponse struct {
	// List of attestation IDs
	AttestationIds []uint64 `protobuf:"varint,1,rep,packed,name=attestation_ids,json=attestationIds,proto3" json:"attestation_ids,omitempty"`
	// Number of blocks that achieved immediate finality
	FinalizedCount uint32 `protobuf:"varint,2,opt,name=finalized_count,json=finalizedCount,proto3" json:"finalized_count,omitempty"`
}

func (m *MsgSubmitBatchBlockAttestationResponse) Reset() {
	*m = MsgSubmitBatchBlockAttestationResponse{}
}
func (m *MsgSubmitBatchBlockAttestationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitBatchBlockAttestationResponse) ProtoMessage()    {}
func (*MsgSubmitBatchBlockAttestationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8903721ed34b385d, []int{4}
}
func (m *MsgSubmitBatchBlockAttestationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitBatchBlockAttestationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitBatchBlockAttestationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitBatchBlockAttestationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitBatchBlockAttestationResponse.Merge(m, src)
}
func (m *MsgSubmitBatchBlockAttestationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitBatchBlockAttestationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitBatchBlockAttestationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitBatchBlockAttestationResponse proto.InternalMessageInfo

func (m *MsgSubmitBatchBlockAttestationResponse) GetAttestationIds() []uint64 {
	if m != nil {
		return m.AttestationIds
	}
	return nil
}

func (m *MsgSubmitBatchBlockAttestationResponse) GetFinalizedCount() uint32 {
	if m != nil {
		return m.FinalizedCount
	}
	return 0
}

// MsgSubmitForcedTransaction wraps a standard Cosmos transaction for forced execution
type MsgSubmitForcedTransaction struct {
	// Address submitting the forced transaction
	Submitter string `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	// Target chain ID where the transaction should be executed
	TargetChainId string `protobuf:"bytes,2,opt,name=target_chain_id,json=targetChainId,proto3" json:"target_chain_id,omitempty"`
	// Target chain type (e.g., "evm", "cosmos")
	TargetChainType string `protobuf:"bytes,3,opt,name=target_chain_type,json=targetChainType,proto3" json:"target_chain_type,omitempty"`
	// Priority level (0-255, higher = more urgent)
	Priority uint32 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	// Transaction type
	TxType ForcedTxType `protobuf:"varint,5,opt,name=tx_type,json=txType,proto3,enum=attestation.v1.ForcedTxType" json:"tx_type,omitempty"`
	// Serialized transaction data (chain-specific format)
	TransactionData []byte `protobuf:"bytes,6,opt,name=transaction_data,json=transactionData,proto3" json:"transaction_data,omitempty"`
	// Deadline block height (0 = no deadline)
	Deadline uint64 `protobuf:"varint,7,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// Optional metadata
	Metadata string `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *MsgSubmitForcedTransaction) Reset()         { *m = MsgSubmitForcedTransaction{} }
func (m *MsgSubmitForcedTransaction) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitForcedTransaction) ProtoMessage()    {}
func (*MsgSubmitForcedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8903721ed34b385d, []int{5}
}
func (m *MsgSubmitForcedTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitForcedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitForcedTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitForcedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitForcedTransaction.Merge(m, src)
}
func (m *MsgSubmitForcedTransaction) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitForcedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitForcedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitForcedTransaction proto.InternalMessageInfo

func (m *MsgSubmitForcedTransaction) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *MsgSubmitForcedTransaction) GetTargetChainId() string {
	if m != nil {
		return m.TargetChainId
	}
	return ""
}

func (m *MsgSubmitForcedTransaction) GetTargetChainType() string {
	if m != nil {
		return m.TargetChainType
	}
	return ""
}

func (m *MsgSubmitForcedTransaction) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *MsgSubmitForcedTransaction) GetTxType() ForcedTxType {
	if m != nil {
		return m.TxType
	}
	return ForcedTxTypeNormal
}

func (m *MsgSubmitForcedTransaction) GetTransactionData() []byte {
	if m != nil {
		return m.TransactionData
	}
	return nil
}

func (m *MsgSubmitForcedTransaction) GetDeadline() uint64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *MsgSubmitForcedTransaction) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

// MsgSubmitForcedTransactionResponse is the response for forced transaction submission
type MsgSubmitForcedTransactionResponse struct {
	// Unique ID for the forced transaction
	ForcedTxId uint64 `protobuf:"varint,1,opt,name=forced_tx_id,json=forcedTxId,proto3" json:"forced_tx_id,omitempty"`
	// Estimated execution block height
	EstimatedExecutionHeight uint64 `protobuf:"varint,2,opt,name=estimated_execution_height,json=estimatedExecutionHeight,proto3" json:"estimated_execution_height,omitempty"`
}

func (m *MsgSubmitForcedTransactionResponse) Reset()         { *m = MsgSubmitForcedTransactionResponse{} }
func (m *MsgSubmitForcedTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitForcedTransactionResponse) ProtoMessage()    {}
func (*MsgSubmitForcedTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8903721ed34b385d, []int{6}
}
func (m *MsgSubmitForcedTransactionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitForcedTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitForcedTransactionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitForcedTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitForcedTransactionResponse.Merge(m, src)
}
func (m *MsgSubmitForcedTransactionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitForcedTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitForcedTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitForcedTransactionResponse proto.InternalMessageInfo

func (m *MsgSubmitForcedTransactionResponse) GetForcedTxId() uint64 {
	if m != nil {
		return m.ForcedTxId
	}
	return 0
}

func (m *MsgSubmitForcedTransactionResponse) GetEstimatedExecutionHeight() uint64 {
	if m != nil {
		return m.EstimatedExecutionHeight
	}
	return 0
}

func init() {
	proto.RegisterEnum("attestation.v1.ForcedTxType", ForcedTxType_name, ForcedTxType_value)
	proto.RegisterType((*MsgSubmitBlockAttestation)(nil), "attestation.v1.MsgSubmitBlockAttestation")
	proto.RegisterType((*MsgSubmitBlockAttestationResponse)(nil), "attestation.v1.MsgSubmitBlockAttestationResponse")
	proto.RegisterType((*MsgSubmitBatchBlockAttestation)(nil), "attestation.v1.MsgSubmitBatchBlockAttestation")
	proto.RegisterType((*BlockAttestationData)(nil), "attestation.v1.BlockAttestationData")
	proto.RegisterType((*MsgSubmitBatchBlockAttestationResponse)(nil), "attestation.v1.MsgSubmitBatchBlockAttestationResponse")
	proto.RegisterType((*MsgSubmitForcedTransaction)(nil), "attestation.v1.MsgSubmitForcedTransaction")
	proto.RegisterType((*MsgSubmitForcedTransactionResponse)(nil), "attestation.v1.MsgSubmitForcedTransactionResponse")
}

func init() { proto.RegisterFile("attestation/v1/tx.proto", fileDescriptor_8903721ed34b385d) }

var fileDescriptor_8903721ed34b385d = []byte{
	// 945 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0x8e, 0x93, 0xd0, 0xa6, 0xb3, 0x69, 0x9b, 0x1d, 0xf5, 0x87, 0xe3, 0xae, 0x22, 0x6f, 0x80,
	0x6d, 0xb6, 0x62, 0x63, 0x35, 0x0b, 0x8b, 0xa8, 0xf6, 0x92, 0xcd, 0xba, 0x4d, 0x25, 0x92, 0xae,
	0x66, 0x23, 0xc4, 0x72, 0xb1, 0xa6, 0xf6, 0xd4, 0xb1, 0x88, 0x3d, 0xc1, 0x9e, 0x44, 0xc9, 0x9e,
	0x38, 0x80, 0x84, 0x72, 0xe2, 0x1f, 0xe8, 0x89, 0x7f, 0x80, 0x7f, 0x02, 0xc4, 0x05, 0x69, 0x8f,
	0x1c, 0x51, 0x7b, 0xe0, 0xc6, 0x9d, 0x1b, 0xf2, 0xd8, 0x71, 0x1c, 0x37, 0x59, 0x75, 0x11, 0x97,
	0xb6, 0xf3, 0xbe, 0xef, 0xcd, 0xbc, 0xf7, 0xbd, 0x6f, 0xc6, 0x05, 0xbb, 0x98, 0x31, 0xe2, 0x31,
	0xcc, 0x2c, 0xea, 0x28, 0xc3, 0x43, 0x85, 0x8d, 0xaa, 0x7d, 0x97, 0x32, 0x0a, 0x37, 0x62, 0x40,
	0x75, 0x78, 0x28, 0x6d, 0x99, 0xd4, 0xa4, 0x1c, 0x52, 0xfc, 0xbf, 0x02, 0x96, 0x54, 0xd4, 0xa9,
	0x67, 0x53, 0x4f, 0x0b, 0x80, 0x60, 0x11, 0x42, 0x77, 0xb1, 0x6d, 0x39, 0x54, 0xe1, 0x3f, 0x83,
	0x50, 0xf9, 0xd7, 0x34, 0x28, 0xb6, 0x3c, 0xf3, 0xe5, 0xe0, 0xdc, 0xb6, 0xd8, 0xb3, 0x1e, 0xd5,
	0xbf, 0xae, 0xcf, 0x0e, 0x81, 0x22, 0x58, 0x75, 0x49, 0x0f, 0x8f, 0x89, 0x2b, 0x0a, 0xb2, 0x50,
	0x59, 0x43, 0xd3, 0x25, 0x2c, 0x82, 0x9c, 0xde, 0xc5, 0x96, 0xa3, 0x59, 0x86, 0x98, 0x0e, 0x20,
	0xbe, 0x3e, 0x35, 0xe0, 0x7d, 0x90, 0x3f, 0xf7, 0x37, 0xd2, 0xba, 0xc4, 0x32, 0xbb, 0x4c, 0xcc,
	0xc8, 0x42, 0x25, 0x8b, 0xee, 0xf0, 0x58, 0x93, 0x87, 0xe0, 0xc7, 0x60, 0xc7, 0x25, 0xdf, 0x0c,
	0x88, 0xc7, 0xb4, 0x0b, 0xcb, 0xc1, 0x3d, 0xeb, 0x35, 0xd1, 0x38, 0x2e, 0x66, 0x65, 0xa1, 0x92,
	0x47, 0x5b, 0x21, 0x7a, 0x1c, 0x82, 0xbc, 0x30, 0xf8, 0x04, 0xec, 0xba, 0xc4, 0xeb, 0x53, 0xc7,
	0x23, 0xc9, 0xb4, 0xf7, 0x78, 0xda, 0xf6, 0x14, 0x9e, 0xcf, 0xbb, 0x07, 0xd6, 0x98, 0x65, 0xfb,
	0x4d, 0xd9, 0x7d, 0x71, 0x45, 0x16, 0x2a, 0x19, 0x34, 0x0b, 0xf8, 0xa8, 0x67, 0x99, 0x0e, 0x66,
	0x03, 0x97, 0x88, 0xab, 0x7c, 0x9f, 0x59, 0xe0, 0x68, 0x7f, 0xf2, 0xd7, 0xcf, 0x07, 0xe5, 0xf8,
	0x44, 0x16, 0x4b, 0x55, 0xee, 0x82, 0xfb, 0x4b, 0x75, 0x44, 0x61, 0x59, 0xf0, 0x43, 0x10, 0x9f,
	0xa1, 0xaf, 0x9d, 0xc0, 0xc5, 0x59, 0x8f, 0x45, 0x4f, 0x0d, 0xbf, 0xa4, 0x69, 0x7f, 0x81, 0xba,
	0x39, 0x34, 0x0b, 0x94, 0x7f, 0x17, 0x40, 0x69, 0x76, 0x14, 0x66, 0x7a, 0xf7, 0xff, 0x99, 0x5b,
	0x13, 0xe4, 0x63, 0x65, 0x78, 0x62, 0x46, 0xce, 0x54, 0xee, 0xd4, 0x3e, 0xa8, 0xce, 0xbb, 0xae,
	0x9a, 0x3c, 0xec, 0x39, 0x66, 0x18, 0xcd, 0x65, 0x1e, 0x7d, 0xe4, 0x8b, 0xb6, 0xbf, 0x40, 0xb4,
	0x45, 0xc5, 0x96, 0x7f, 0x11, 0xc0, 0xd6, 0xa2, 0x4d, 0x6f, 0x18, 0x49, 0x78, 0x17, 0x23, 0xa5,
	0xff, 0x9b, 0x91, 0x32, 0xb7, 0x36, 0x52, 0x36, 0x61, 0xa4, 0xf2, 0x6b, 0xf0, 0xe0, 0xed, 0x63,
	0x89, 0x6c, 0xb0, 0x0f, 0x36, 0xe7, 0x6d, 0xe0, 0x89, 0x82, 0x9c, 0xa9, 0x64, 0xd1, 0xc6, 0x9c,
	0x0f, 0x3c, 0x9f, 0x18, 0xcd, 0x5d, 0xd3, 0xe9, 0xc0, 0x61, 0xbc, 0xaf, 0x75, 0xb4, 0x11, 0x85,
	0x1b, 0x7e, 0xb4, 0xfc, 0x77, 0x1a, 0x48, 0xd1, 0xe1, 0xc7, 0xd4, 0xd5, 0x89, 0xd1, 0x71, 0xb1,
	0xe3, 0x61, 0x9d, 0xfb, 0xc1, 0xf7, 0x38, 0x87, 0x58, 0xe4, 0x88, 0x59, 0x00, 0x3e, 0x00, 0x9b,
	0x0c, 0xbb, 0x26, 0x61, 0x5a, 0xc2, 0x1a, 0xeb, 0x41, 0xb8, 0x11, 0x1a, 0xe4, 0x00, 0xdc, 0x9d,
	0xe3, 0xb1, 0x71, 0x9f, 0x70, 0xc1, 0xd6, 0xd0, 0x66, 0x8c, 0xd9, 0x19, 0xf7, 0x09, 0x94, 0x40,
	0xae, 0xef, 0x5a, 0xd4, 0xb5, 0xd8, 0x98, 0x2b, 0xb5, 0x8e, 0xa2, 0x35, 0xfc, 0x04, 0xac, 0xb2,
	0x51, 0x90, 0xed, 0xdf, 0xdb, 0x8d, 0xda, 0xbd, 0xa4, 0xc7, 0xc2, 0x0e, 0x46, 0xfe, 0x56, 0x68,
	0x85, 0xf1, 0xdf, 0xf0, 0x21, 0x28, 0xb0, 0x59, 0x4f, 0x9a, 0x81, 0x19, 0xe6, 0xb7, 0x39, 0x8f,
	0x36, 0x63, 0x71, 0xee, 0x1c, 0x09, 0xe4, 0x0c, 0x82, 0x8d, 0x9e, 0xe5, 0x04, 0x57, 0x3a, 0x8b,
	0xa2, 0xb5, 0x8f, 0xd9, 0x84, 0x61, 0x9e, 0x9e, 0xe3, 0xc5, 0x47, 0xeb, 0xa3, 0x8a, 0x6f, 0xdc,
	0xf7, 0x6f, 0x1a, 0xf7, 0x86, 0xa2, 0xe5, 0xef, 0x04, 0x50, 0x5e, 0x2e, 0x78, 0x34, 0x69, 0x19,
	0xe4, 0x2f, 0x38, 0xa8, 0xb1, 0xd1, 0xec, 0xba, 0x83, 0x8b, 0xb0, 0xbf, 0x53, 0x03, 0x3e, 0x05,
	0x12, 0xf1, 0x98, 0x65, 0x63, 0x46, 0x0c, 0x8d, 0x8c, 0x88, 0x3e, 0xe0, 0xdd, 0x85, 0x96, 0x4f,
	0x73, 0xbe, 0x18, 0x31, 0xd4, 0x29, 0x21, 0xf0, 0xff, 0xc1, 0x3f, 0x02, 0xc8, 0xc7, 0xc5, 0x82,
	0x87, 0x60, 0xfb, 0xf8, 0x0c, 0x35, 0xd4, 0xe7, 0x5a, 0xe7, 0x4b, 0xad, 0xf3, 0xea, 0x85, 0xaa,
	0xb5, 0xcf, 0x50, 0xab, 0xfe, 0x79, 0x21, 0x25, 0xed, 0x4c, 0x2e, 0x65, 0x18, 0x27, 0xb7, 0xa9,
	0x6b, 0xe3, 0x1e, 0xfc, 0x0c, 0x14, 0x13, 0x29, 0x27, 0x67, 0x5f, 0xa8, 0xa8, 0x5d, 0x6f, 0x37,
	0xd4, 0x82, 0x20, 0x49, 0x93, 0x4b, 0x79, 0x27, 0x9e, 0x76, 0x42, 0x87, 0xc4, 0x75, 0xb0, 0xa3,
	0x13, 0xf8, 0x14, 0xec, 0x25, 0x52, 0xd5, 0x97, 0x8d, 0xfa, 0x0b, 0x55, 0x6b, 0xd6, 0x3b, 0x8d,
	0x66, 0x21, 0x2d, 0xed, 0x4d, 0x2e, 0xe5, 0xdd, 0x78, 0xb2, 0xea, 0xe9, 0xb8, 0x4f, 0x9a, 0xfe,
	0xf5, 0x80, 0x9f, 0x02, 0x31, 0x99, 0xdd, 0x52, 0xd1, 0x89, 0xda, 0x6e, 0xbc, 0x2a, 0x64, 0xa4,
	0xe2, 0xe4, 0x52, 0xde, 0x9e, 0x4b, 0xb5, 0x89, 0x6b, 0x12, 0x47, 0x1f, 0x4b, 0xd9, 0x1f, 0x7e,
	0x2a, 0xa5, 0x6a, 0xdf, 0x66, 0x40, 0xa6, 0xe5, 0x99, 0x70, 0x08, 0x76, 0x96, 0x7c, 0xbe, 0x1e,
	0x26, 0x7d, 0xb5, 0xf4, 0x85, 0x96, 0x0e, 0x6f, 0x4d, 0x8d, 0x66, 0xfb, 0xbd, 0x00, 0xf6, 0xde,
	0xf6, 0x08, 0x57, 0x97, 0x6f, 0xb9, 0x88, 0x2f, 0x3d, 0x79, 0x37, 0x7e, 0x54, 0xc7, 0x18, 0xec,
	0x2e, 0xbb, 0xf7, 0x07, 0x4b, 0xb7, 0xbc, 0xc1, 0x95, 0x6a, 0xb7, 0xe7, 0x4e, 0x8f, 0x7e, 0xd6,
	0xfa, 0xed, 0xaa, 0x24, 0xbc, 0xb9, 0x2a, 0x09, 0x7f, 0x5e, 0x95, 0x84, 0x1f, 0xaf, 0x4b, 0xa9,
	0x37, 0xd7, 0xa5, 0xd4, 0x1f, 0xd7, 0xa5, 0xd4, 0x57, 0x8f, 0x4d, 0x8b, 0x75, 0x07, 0xe7, 0x55,
	0x9d, 0xda, 0x8a, 0xee, 0x8e, 0xfb, 0x8c, 0x3e, 0xa2, 0xae, 0xf9, 0x88, 0x3f, 0x1c, 0x8a, 0xee,
	0x52, 0x87, 0x7a, 0xca, 0xb0, 0xa6, 0x84, 0x9f, 0x25, 0xc5, 0x7f, 0x0c, 0xbc, 0xf3, 0x15, 0xfe,
	0x3f, 0xc9, 0xe3, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xec, 0xb7, 0x5c, 0x23, 0x02, 0x09, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SubmitBlockAttestation submits block finalization data from an EVM chain
	SubmitBlockAttestation(ctx context.Context, in *MsgSubmitBlockAttestation, opts ...grpc.CallOption) (*MsgSubmitBlockAttestationResponse, error)
	// SubmitBatchBlockAttestation submits multiple block attestations
	SubmitBatchBlockAttestation(ctx context.Context, in *MsgSubmitBatchBlockAttestation, opts ...grpc.CallOption) (*MsgSubmitBatchBlockAttestationResponse, error)
	// SubmitForcedTransaction submits a forced transaction to be executed on target chain
	SubmitForcedTransaction(ctx context.Context, in *MsgSubmitForcedTransaction, opts ...grpc.CallOption) (*MsgSubmitForcedTransactionResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitBlockAttestation(ctx context.Context, in *MsgSubmitBlockAttestation, opts ...grpc.CallOption) (*MsgSubmitBlockAttestationResponse, error) {
	out := new(MsgSubmitBlockAttestationResponse)
	err := c.cc.Invoke(ctx, "/attestation.v1.Msg/SubmitBlockAttestation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitBatchBlockAttestation(ctx context.Context, in *MsgSubmitBatchBlockAttestation, opts ...grpc.CallOption) (*MsgSubmitBatchBlockAttestationResponse, error) {
	out := new(MsgSubmitBatchBlockAttestationResponse)
	err := c.cc.Invoke(ctx, "/attestation.v1.Msg/SubmitBatchBlockAttestation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitForcedTransaction(ctx context.Context, in *MsgSubmitForcedTransaction, opts ...grpc.CallOption) (*MsgSubmitForcedTransactionResponse, error) {
	out := new(MsgSubmitForcedTransactionResponse)
	err := c.cc.Invoke(ctx, "/attestation.v1.Msg/SubmitForcedTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SubmitBlockAttestation submits block finalization data from an EVM chain
	SubmitBlockAttestation(context.Context, *MsgSubmitBlockAttestation) (*MsgSubmitBlockAttestationResponse, error)
	// SubmitBatchBlockAttestation submits multiple block attestations
	SubmitBatchBlockAttestation(context.Context, *MsgSubmitBatchBlockAttestation) (*MsgSubmitBatchBlockAttestationResponse, error)
	// SubmitForcedTransaction submits a forced transaction to be executed on target chain
	SubmitForcedTransaction(context.Context, *MsgSubmitForcedTransaction) (*MsgSubmitForcedTransactionResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitBlockAttestation(ctx context.Context, req *MsgSubmitBlockAttestation) (*MsgSubmitBlockAttestationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitBlockAttestation not implemented")
}
func (*UnimplementedMsgServer) SubmitBatchBlockAttestation(ctx context.Context, req *MsgSubmitBatchBlockAttestation) (*MsgSubmitBatchBlockAttestationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitBatchBlockAttestation not implemented")
}
func (*UnimplementedMsgServer) SubmitForcedTransaction(ctx context.Context, req *MsgSubmitForcedTransaction) (*MsgSubmitForcedTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitForcedTransaction not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitBlockAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitBlockAttestation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitBlockAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/attestation.v1.Msg/SubmitBlockAttestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitBlockAttestation(ctx, req.(*MsgSubmitBlockAttestation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitBatchBlockAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitBatchBlockAttestation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitBatchBlockAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/attestation.v1.Msg/SubmitBatchBlockAttestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitBatchBlockAttestation(ctx, req.(*MsgSubmitBatchBlockAttestation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitForcedTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitForcedTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitForcedTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/attestation.v1.Msg/SubmitForcedTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitForcedTransaction(ctx, req.(*MsgSubmitForcedTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "attestation.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitBlockAttestation",
			Handler:    _Msg_SubmitBlockAttestation_Handler,
		},
		{
			MethodName: "SubmitBatchBlockAttestation",
			Handler:    _Msg_SubmitBatchBlockAttestation_Handler,
		},
		{
			MethodName: "SubmitForcedTransaction",
			Handler:    _Msg_SubmitForcedTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "attestation/v1/tx.proto",
}

func (m *MsgSubmitBlockAttestation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitBlockAttestation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitBlockAttestation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Timestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ResponseFinalizeBlock) > 0 {
		i -= len(m.ResponseFinalizeBlock)
		copy(dAtA[i:], m.ResponseFinalizeBlock)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ResponseFinalizeBlock)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.RequestFinalizeBlock) > 0 {
		i -= len(m.RequestFinalizeBlock)
		copy(dAtA[i:], m.RequestFinalizeBlock)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RequestFinalizeBlock)))
		i--
		dAtA[i] = 0x22
	}
	if m.BlockHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Relayer) > 0 {
		i -= len(m.Relayer)
		copy(dAtA[i:], m.Relayer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Relayer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitBlockAttestationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitBlockAttestationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitBlockAttestationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Finalized {
		i--
		if m.Finalized {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.AttestationId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.AttestationId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitBatchBlockAttestation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitBatchBlockAttestation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitBatchBlockAttestation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Attestations) > 0 {
		for iNdEx := len(m.Attestations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attestations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Relayer) > 0 {
		i -= len(m.Relayer)
		copy(dAtA[i:], m.Relayer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Relayer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BlockAttestationData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlockAttestationData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlockAttestationData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ResponseFinalizeBlock) > 0 {
		i -= len(m.ResponseFinalizeBlock)
		copy(dAtA[i:], m.ResponseFinalizeBlock)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ResponseFinalizeBlock)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RequestFinalizeBlock) > 0 {
		i -= len(m.RequestFinalizeBlock)
		copy(dAtA[i:], m.RequestFinalizeBlock)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RequestFinalizeBlock)))
		i--
		dAtA[i] = 0x12
	}
	if m.BlockHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitBatchBlockAttestationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitBatchBlockAttestationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitBatchBlockAttestationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FinalizedCount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FinalizedCount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.AttestationIds) > 0 {
		dAtA2 := make([]byte, len(m.AttestationIds)*10)
		var j1 int
		for _, num := range m.AttestationIds {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintTx(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitForcedTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitForcedTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitForcedTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metadata) > 0 {
		i -= len(m.Metadata)
		copy(dAtA[i:], m.Metadata)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Metadata)))
		i--
		dAtA[i] = 0x42
	}
	if m.Deadline != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Deadline))
		i--
		dAtA[i] = 0x38
	}
	if len(m.TransactionData) > 0 {
		i -= len(m.TransactionData)
		copy(dAtA[i:], m.TransactionData)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TransactionData)))
		i--
		dAtA[i] = 0x32
	}
	if m.TxType != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TxType))
		i--
		dAtA[i] = 0x28
	}
	if m.Priority != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Priority))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TargetChainType) > 0 {
		i -= len(m.TargetChainType)
		copy(dAtA[i:], m.TargetChainType)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TargetChainType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TargetChainId) > 0 {
		i -= len(m.TargetChainId)
		copy(dAtA[i:], m.TargetChainId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TargetChainId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitForcedTransactionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitForcedTransactionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitForcedTransactionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EstimatedExecutionHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EstimatedExecutionHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.ForcedTxId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ForcedTxId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSubmitBlockAttestation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Relayer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovTx(uint64(m.BlockHeight))
	}
	l = len(m.RequestFinalizeBlock)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ResponseFinalizeBlock)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovTx(uint64(m.Timestamp))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitBlockAttestationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AttestationId != 0 {
		n += 1 + sovTx(uint64(m.AttestationId))
	}
	if m.Finalized {
		n += 2
	}
	return n
}

func (m *MsgSubmitBatchBlockAttestation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Relayer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Attestations) > 0 {
		for _, e := range m.Attestations {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *BlockAttestationData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovTx(uint64(m.BlockHeight))
	}
	l = len(m.RequestFinalizeBlock)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ResponseFinalizeBlock)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovTx(uint64(m.Timestamp))
	}
	return n
}

func (m *MsgSubmitBatchBlockAttestationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AttestationIds) > 0 {
		l = 0
		for _, e := range m.AttestationIds {
			l += sovTx(uint64(e))
		}
		n += 1 + sovTx(uint64(l)) + l
	}
	if m.FinalizedCount != 0 {
		n += 1 + sovTx(uint64(m.FinalizedCount))
	}
	return n
}

func (m *MsgSubmitForcedTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TargetChainId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TargetChainType)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Priority != 0 {
		n += 1 + sovTx(uint64(m.Priority))
	}
	if m.TxType != 0 {
		n += 1 + sovTx(uint64(m.TxType))
	}
	l = len(m.TransactionData)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Deadline != 0 {
		n += 1 + sovTx(uint64(m.Deadline))
	}
	l = len(m.Metadata)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitForcedTransactionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ForcedTxId != 0 {
		n += 1 + sovTx(uint64(m.ForcedTxId))
	}
	if m.EstimatedExecutionHeight != 0 {
		n += 1 + sovTx(uint64(m.EstimatedExecutionHeight))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSubmitBlockAttestation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitBlockAttestation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitBlockAttestation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Relayer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Relayer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestFinalizeBlock", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestFinalizeBlock = append(m.RequestFinalizeBlock[:0], dAtA[iNdEx:postIndex]...)
			if m.RequestFinalizeBlock == nil {
				m.RequestFinalizeBlock = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResponseFinalizeBlock", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResponseFinalizeBlock = append(m.ResponseFinalizeBlock[:0], dAtA[iNdEx:postIndex]...)
			if m.ResponseFinalizeBlock == nil {
				m.ResponseFinalizeBlock = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitBlockAttestationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitBlockAttestationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitBlockAttestationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationId", wireType)
			}
			m.AttestationId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AttestationId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Finalized", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Finalized = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitBatchBlockAttestation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitBatchBlockAttestation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitBatchBlockAttestation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Relayer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Relayer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attestations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attestations = append(m.Attestations, &BlockAttestationData{})
			if err := m.Attestations[len(m.Attestations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BlockAttestationData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlockAttestationData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlockAttestationData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestFinalizeBlock", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestFinalizeBlock = append(m.RequestFinalizeBlock[:0], dAtA[iNdEx:postIndex]...)
			if m.RequestFinalizeBlock == nil {
				m.RequestFinalizeBlock = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResponseFinalizeBlock", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResponseFinalizeBlock = append(m.ResponseFinalizeBlock[:0], dAtA[iNdEx:postIndex]...)
			if m.ResponseFinalizeBlock == nil {
				m.ResponseFinalizeBlock = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitBatchBlockAttestationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitBatchBlockAttestationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitBatchBlockAttestationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.AttestationIds = append(m.AttestationIds, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.AttestationIds) == 0 {
					m.AttestationIds = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.AttestationIds = append(m.AttestationIds, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationIds", wireType)
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedCount", wireType)
			}
			m.FinalizedCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinalizedCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitForcedTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitForcedTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitForcedTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetChainType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetChainType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Priority", wireType)
			}
			m.Priority = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Priority |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxType", wireType)
			}
			m.TxType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxType |= ForcedTxType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransactionData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransactionData = append(m.TransactionData[:0], dAtA[iNdEx:postIndex]...)
			if m.TransactionData == nil {
				m.TransactionData = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deadline", wireType)
			}
			m.Deadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Deadline |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metadata = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitForcedTransactionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitForcedTransactionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitForcedTransactionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForcedTxId", wireType)
			}
			m.ForcedTxId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ForcedTxId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EstimatedExecutionHeight", wireType)
			}
			m.EstimatedExecutionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EstimatedExecutionHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
