// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: attestation/v1/events.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventBatchBlockAttested is emitted for batch attestations
type EventBatchBlockAttested struct {
	// Source chain ID
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Rollup address who submitted the batch
	RollupAddress string `protobuf:"bytes,2,opt,name=rollup_address,json=rollupAddress,proto3" json:"rollup_address,omitempty"`
	// List of attestation IDs
	AttestationIds []uint64 `protobuf:"varint,3,rep,packed,name=attestation_ids,json=attestationIds,proto3" json:"attestation_ids,omitempty"`
	// List of block heights that were attested
	AttestBlockHeights []uint64 `protobuf:"varint,4,rep,packed,name=attest_block_heights,json=attestBlockHeights,proto3" json:"attest_block_heights,omitempty"`
	// Finality timestamp (0 if not finalized)
	FinalizedAt int64 `protobuf:"varint,5,opt,name=finalized_at,json=finalizedAt,proto3" json:"finalized_at,omitempty"`
	// Finality proof (validator signatures, etc.)
	FinalityProof []byte `protobuf:"bytes,6,opt,name=finality_proof,json=finalityProof,proto3" json:"finality_proof,omitempty"`
}

func (m *EventBatchBlockAttested) Reset()         { *m = EventBatchBlockAttested{} }
func (m *EventBatchBlockAttested) String() string { return proto.CompactTextString(m) }
func (*EventBatchBlockAttested) ProtoMessage()    {}
func (*EventBatchBlockAttested) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae226af17978ceef, []int{0}
}
func (m *EventBatchBlockAttested) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBatchBlockAttested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBatchBlockAttested.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBatchBlockAttested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBatchBlockAttested.Merge(m, src)
}
func (m *EventBatchBlockAttested) XXX_Size() int {
	return m.Size()
}
func (m *EventBatchBlockAttested) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBatchBlockAttested.DiscardUnknown(m)
}

var xxx_messageInfo_EventBatchBlockAttested proto.InternalMessageInfo

func (m *EventBatchBlockAttested) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *EventBatchBlockAttested) GetRollupAddress() string {
	if m != nil {
		return m.RollupAddress
	}
	return ""
}

func (m *EventBatchBlockAttested) GetAttestationIds() []uint64 {
	if m != nil {
		return m.AttestationIds
	}
	return nil
}

func (m *EventBatchBlockAttested) GetAttestBlockHeights() []uint64 {
	if m != nil {
		return m.AttestBlockHeights
	}
	return nil
}

func (m *EventBatchBlockAttested) GetFinalizedAt() int64 {
	if m != nil {
		return m.FinalizedAt
	}
	return 0
}

func (m *EventBatchBlockAttested) GetFinalityProof() []byte {
	if m != nil {
		return m.FinalityProof
	}
	return nil
}

func init() {
	proto.RegisterType((*EventBatchBlockAttested)(nil), "attestation.v1.EventBatchBlockAttested")
}

func init() { proto.RegisterFile("attestation/v1/events.proto", fileDescriptor_ae226af17978ceef) }

var fileDescriptor_ae226af17978ceef = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xd7, 0x6d, 0x4e, 0xad, 0xdb, 0x84, 0x32, 0xb0, 0x2a, 0x94, 0x2a, 0x88, 0xbd, 0x6c,
	0x71, 0x08, 0xde, 0x37, 0x10, 0xdc, 0x6d, 0xf4, 0xe8, 0x25, 0x64, 0x4d, 0xd6, 0x06, 0x6b, 0x5f,
	0x49, 0xde, 0x86, 0xf3, 0xe4, 0x47, 0xf0, 0x63, 0x79, 0xdc, 0xd1, 0xa3, 0x6c, 0x5f, 0x44, 0x9a,
	0xa0, 0xf4, 0x96, 0xf7, 0xfb, 0xff, 0x1f, 0xfc, 0x78, 0x71, 0x2f, 0x19, 0xa2, 0xd0, 0xc8, 0x50,
	0x42, 0x41, 0xd6, 0x63, 0x22, 0xd6, 0xa2, 0x40, 0x3d, 0x2a, 0x15, 0x20, 0x78, 0xfd, 0x5a, 0x38,
	0x5a, 0x8f, 0x2f, 0x06, 0x29, 0xa4, 0x60, 0x22, 0x52, 0xbd, 0x6c, 0xeb, 0xfa, 0xa3, 0xe9, 0x9e,
	0x3d, 0x56, 0x6b, 0x53, 0x86, 0x49, 0x36, 0xcd, 0x21, 0x79, 0x99, 0x98, 0x3d, 0xc1, 0xbd, 0x73,
	0xf7, 0x28, 0xc9, 0x98, 0x2c, 0xa8, 0xe4, 0xbe, 0x13, 0x3a, 0xd1, 0x71, 0x7c, 0x68, 0xe6, 0x19,
	0xf7, 0x6e, 0xdc, 0xbe, 0x82, 0x3c, 0x5f, 0x95, 0x94, 0x71, 0xae, 0x84, 0xd6, 0x7e, 0xd3, 0x14,
	0x7a, 0x96, 0x4e, 0x2c, 0xf4, 0x6e, 0xdd, 0xd3, 0x9a, 0x05, 0x95, 0x5c, 0xfb, 0xad, 0xb0, 0x15,
	0xb5, 0xe3, 0xba, 0xdc, 0x8c, 0x6b, 0xef, 0xce, 0x1d, 0x58, 0x42, 0x17, 0x95, 0x02, 0xcd, 0x84,
	0x4c, 0x33, 0xd4, 0x7e, 0xdb, 0xb4, 0x3d, 0x9b, 0x19, 0xbb, 0x27, 0x9b, 0x78, 0x57, 0x6e, 0x77,
	0x29, 0x0b, 0x96, 0xcb, 0x77, 0xc1, 0x29, 0x43, 0xff, 0x20, 0x74, 0xa2, 0x56, 0x7c, 0xf2, 0xcf,
	0x26, 0x58, 0x49, 0xda, 0x11, 0x37, 0xb4, 0x54, 0x00, 0x4b, 0xbf, 0x13, 0x3a, 0x51, 0x37, 0xee,
	0xfd, 0xd1, 0x79, 0x05, 0xa7, 0xf3, 0xaf, 0x5d, 0xe0, 0x6c, 0x77, 0x81, 0xf3, 0xb3, 0x0b, 0x9c,
	0xcf, 0x7d, 0xd0, 0xd8, 0xee, 0x83, 0xc6, 0xf7, 0x3e, 0x68, 0x3c, 0x3f, 0xa4, 0x12, 0xb3, 0xd5,
	0x62, 0x94, 0xc0, 0x2b, 0x49, 0xd4, 0xa6, 0x44, 0x18, 0x82, 0x4a, 0x87, 0xe6, 0x08, 0x24, 0x51,
	0x50, 0x80, 0x26, 0x6f, 0xa4, 0xfe, 0x09, 0xb8, 0x29, 0x85, 0x5e, 0x74, 0xcc, 0x6d, 0xef, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x33, 0xc2, 0x4a, 0x6e, 0xa0, 0x01, 0x00, 0x00,
}

func (m *EventBatchBlockAttested) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBatchBlockAttested) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBatchBlockAttested) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FinalityProof) > 0 {
		i -= len(m.FinalityProof)
		copy(dAtA[i:], m.FinalityProof)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.FinalityProof)))
		i--
		dAtA[i] = 0x32
	}
	if m.FinalizedAt != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.FinalizedAt))
		i--
		dAtA[i] = 0x28
	}
	if len(m.AttestBlockHeights) > 0 {
		dAtA2 := make([]byte, len(m.AttestBlockHeights)*10)
		var j1 int
		for _, num := range m.AttestBlockHeights {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintEvents(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AttestationIds) > 0 {
		dAtA4 := make([]byte, len(m.AttestationIds)*10)
		var j3 int
		for _, num := range m.AttestationIds {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintEvents(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RollupAddress) > 0 {
		i -= len(m.RollupAddress)
		copy(dAtA[i:], m.RollupAddress)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.RollupAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventBatchBlockAttested) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.RollupAddress)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if len(m.AttestationIds) > 0 {
		l = 0
		for _, e := range m.AttestationIds {
			l += sovEvents(uint64(e))
		}
		n += 1 + sovEvents(uint64(l)) + l
	}
	if len(m.AttestBlockHeights) > 0 {
		l = 0
		for _, e := range m.AttestBlockHeights {
			l += sovEvents(uint64(e))
		}
		n += 1 + sovEvents(uint64(l)) + l
	}
	if m.FinalizedAt != 0 {
		n += 1 + sovEvents(uint64(m.FinalizedAt))
	}
	l = len(m.FinalityProof)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventBatchBlockAttested) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBatchBlockAttested: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBatchBlockAttested: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollupAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEvents
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.AttestationIds = append(m.AttestationIds, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEvents
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthEvents
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthEvents
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.AttestationIds) == 0 {
					m.AttestationIds = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEvents
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.AttestationIds = append(m.AttestationIds, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationIds", wireType)
			}
		case 4:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEvents
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.AttestBlockHeights = append(m.AttestBlockHeights, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEvents
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthEvents
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthEvents
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.AttestBlockHeights) == 0 {
					m.AttestBlockHeights = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEvents
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.AttestBlockHeights = append(m.AttestBlockHeights, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestBlockHeights", wireType)
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedAt", wireType)
			}
			m.FinalizedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinalizedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalityProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalityProof = append(m.FinalityProof[:0], dAtA[iNdEx:postIndex]...)
			if m.FinalityProof == nil {
				m.FinalityProof = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
