#!/bin/sh
make -C contracts
cat contracts/out/dapp.sol.json | \
    jq '.contracts."src/ModuleCRC20.sol".ModuleCRC20' | \
    jq '{abi, bin: .evm.bytecode.object}' \
    > x/cronos/types/contracts/ModuleCRC20.json
