#!/bin/sh
set -e
cd "$(dirname "$0")"

# explicitly set a short TMPDIR to prevent path too long issue on macosx
export TMPDIR=/tmp

echo "build test contracts"
cd ../integration_tests/contracts
( flock -w 60 -n 9 || exit 1;
HUSKY_SKIP_INSTALL=1 npm install
npm run typechain
) 9> lockfile
cd ..
TESTS_TO_RUN="${TESTS_TO_RUN:-all}"
if [[ "$TESTS_TO_RUN" == "all" ]]; then
  echo "run all tests"
  cmd="pytest -vv -s"
else
  echo "run tests matching $TESTS_TO_RUN"
  cmd="pytest -vv -s -m '$TESTS_TO_RUN'"
fi
nix-shell --run "$cmd"
