#!/bin/sh
set -e

CONFIG=$1
if [ -z $CONFIG ]; then
    echo "No config file supplied"
    exit 1
fi
shift

DATA=$1
if [ -z $DATA ]; then
    echo "No data directory supplied"
    exit 1
fi
shift

geth --datadir $DATA init $CONFIG
pwdfile=$(mktemp /tmp/password.XXXXXX)
tmpfile=$(mktemp /tmp/validator-key.XXXXXX)

cat > $pwdfile << EOF
$PASSWORD
EOF

# import validator key
cat > $tmpfile << EOF
$VALIDATOR_KEY
EOF
geth --datadir $DATA account import $tmpfile --password $pwdfile

# import community key
cat > $tmpfile << EOF
$COMMUNITY_KEY
EOF
geth --datadir $DATA account import $tmpfile --password $pwdfile

rm $tmpfile

# start up
geth --networkid 777 --datadir $DATA --http --http.addr localhost --http.api 'personal,eth,net,web3,txpool,miner' \
-unlock '0x57f96e6b86cdefdb3d412547816a82e3e0ebf9d2' --password $pwdfile \
--mine --allow-insecure-unlock \
$@

rm $pwdfile
