name: Run Gosec
on:
  pull_request:
  push:
    branches:
      - main
      - release/**

jobs:
  Gosec:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@f27caffdd0fb9b13f4fc191c016bb4e0632844af # v3
        with:
          SUFFIX_FILTER: |
            .go
            .mod
            .sum
      - name: Run Gosec Security Scanner
        uses: informalsystems/gosec@f3d05e8e90198e1d4823cf4e8cb36ad490df8677 # v0.10.4
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: '-no-fail -fmt sarif -out results.sarif ./...'
        if: "env.GIT_DIFF_FILTERED != ''"
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
        if: "env.GIT_DIFF_FILTERED != ''"
