name: "Issue Labeler"
on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.4
        if: ${{ github.event.issue.labels == '' || github.event.issue.labels == null }}
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/issue_labeler.yml
          enable-versioned-regex: 0 
