name: "Issue Labeler"
on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.4
        # run only when the issue currently has NO labels
        if: ${{ join(github.event.issue.labels.*.name, '') == '' }}
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/issue_labeler.yml
          enable-versioned-regex: 0 
