name: release

on:
  push:
    branches:
      - feature/452  
  
jobs:
  windows-rocksdb-x86_64:    
    runs-on: windows-latest
    environment: release    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: msys2/setup-msys2@v2 
      - shell: msys2 {0}
        run: |
          uname -a               

