name: release

on:
  push:
    branches:
      - feature/452  
  
jobs:
  windows-rocksdb-x86_64:    
    runs-on: windows-latest
    environment: release    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: msys2-devel base-devel mingw-w64-cross-gcc mingw-w64-x86_64-rocksdb  mingw-w64-x86_64-go  mingw-w64-x86_64-jq  mingw-w64-x86_64-dlfcn        
      - shell: msys2 {0}
        run: |
          uname -a
          export COSMOS_BUILD_OPTIONS=rocksdb   
          make             

