name: release

on:
  push:
    branches:
      - feature/452  
  
jobs:
  windows-rocksdb-x86_64:    
    runs-on: windows-latest
    environment: release    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: git msys2-devel base-devel mingw-w64-x86_64-gcc mingw-w64-x86_64-rocksdb  mingw-w64-x86_64-go  mingw-w64-x86_64-jq  mingw-w64-x86_64-dlfcn        
      - shell: msys2 {0}
        run: |
          uname -a
          export GOROOT=/mingw64/lib/go
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
          export COSMOS_BUILD_OPTIONS=rocksdb   
          export CGO_CFLAGS="-I/mingw64/include/rocksdb" 
          export CGO_LDFLAGS="-L/mingw64/lib -lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy -llz4 -lzstd" 
          echo $PATH
          go version
          make             

